server:
  port: 8082

upload:
  directory: uploads

spring:
  application:
    name: product
  config:
    import: optional:configserver:${CONFIG_SERVICE_URL:http://localhost:8888}
  profiles:
    active: dev
  security:
    oauth2:
      resourceserver:
        jwt:
          jwt-issue-uri: http://localhost:8080/realms/OnlineOrderManagement-Realm
          jwk-set-uri: http://localhost:8080/realms/OnlineOrderManagement-Realm/protocol/openid-connect/certs
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB