server:
  port: 8765

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          "[/**]": # Appliquer à toutes les routes
            allowedOrigins:
              - "http://localhost:3000" # Autoriser uniquement React sur le port 3000
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
            allowCredentials: true
eureka:
  client:
    service-url:
      # defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: "*"
