server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Oussalem-zakaria/OnlineOrderManagementConfig.git
          clone-on-start: true

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://eureka-server:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: "health,info,env,refresh"
